version: '3.8'
services:
    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
            POSTGRES_DB: books_db
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
